### ISSUE TITLE
simplify default compare functions

### ISSUE THREAD

**Issue by nkappler** [ignlg/heap-js#143]
you can use `(a, b) => a-b`, `(a, b) => b-a` for the default minComparator and maxComparator function respectively.
Should be a bit faster than the `if -> else if -> else`

**Comment by nkappler** [comment]
of course this would work only for numbers.
This happens when you open up issues in the middle of the nigh 😅

**Comment by ignlg** [comment]
Totally agree, indeed they are available as static functions at

https://github.com/ignlg/heap-js/blob/7fd31cc60776e00616fd38cdaba4e72c601c96e4/src/Heap.ts#L112

and

https://github.com/ignlg/heap-js/blob/7fd31cc60776e00616fd38cdaba4e72c601c96e4/src/Heap.ts#L122

Thanks for your feedback @nkappler 👍
