### ISSUE TITLE
Issue popping when using custom comparator

### ISSUE THREAD

**Issue by bjrnt** [ignlg/heap-js#31]
Hi,

Thanks for the library! I've had great use of it in a lot of online coding interviews. :)

Here's a quick reproduction of a bug I found when using custom comparators:
```js
const heap = new Heap((a, b) => a[1] - b[1]);
heap.push([1, 2]);
heap.push([6, 0]);
heap.push([2, 3]);
heap.pop();
// => TypeError: Cannot read property '1' of undefined
```

After some digging, I found that inside `getPotentialParent` sometimes calls `this.compare` with an `undefined` value. Adding a quick `typeof this.heapArray[j] !== "undefined" &&` to the function solves the issue but I am not sure if this is the best way to handle it. I'd be happy to send a PR with tests if you think this is a good solution to the problem.

**Comment by ignlg** [comment]
Hello @bjrnt, thanks for your feedback. I will try it within the `next` branch to be sure that it is not already fixed.

**Comment by ignlg** [comment]
It should be fixed now.

To allow `undefined` as a valid value inside the heap, it checks that the index is not beyond length before any comparison occurs.

I have added tests for custom heaps with custom comparators, and improved the existing ones.

@bjrnt Could you try the `next` branch and let me know if it fixed the issue for you?

Thanks :)

**Comment by bjrnt** [comment]
Yep, working great now! Thanks for the quick fix! :)
