### ISSUE TITLE
When the priorities are equal, shouldn't the FIFO principle be followed, but it's not

### ISSUE THREAD

**Issue by ash0080** [ignlg/heap-js#460]
```
const Heap = require('heap-js').default

const comparator = (a, b) => {
    if (a.ttl > b.ttl) {
        return 1
    }
    if (a.ttl < b.ttl) {
        return -1
    }
    return 0
}

const equalSamples = [{ id: 1, ttl: 0 }, { id: 2, ttl: 0 }, { id: 3, ttl: 0 }, { id: 4, ttl: 0 }]
it('FIFO when equal compare', () => {
    const heap = new Heap(comparator)
    heap.push(...equalSamples)
    expect([heap.pop(), heap.pop(), heap.pop(), heap.pop()]).toEqual(equalSamples)
})

```

failed

Consider a sequence that is constantly push() and pop(). If FIFO is not followed, some tasks will never be pop() as long as the sequence is constantly push().

**Comment by ignlg** [comment]
Hi @ash0080, sorry for the delay.

Interesting approach, I will do some deep tests with your data and should be back with some answers soon.

Thanks for your feedback! :)

**Comment by ignlg** [comment]
I'm back. After doing some tests, the behavior is right.

The [heap data structure algorithm](https://www.tutorialspoint.com/data_structures_algorithms/heap_data_structure.htm) establishes that **when the top/peek node is removed** (`id:1`), **the latest leaf** (`id:4`) **should be promoted as the new top/peek** and the sorting algorithm is triggered.

As all the elements are equally weighted, `id:4` is a valid top node and the tree is stable.

When you pop the top node again (`id:4`), the latest leaf (`id:3`) is promoted as the new top and, as it is a valid top node, the tree is stable again. 

The predictable sequence of values is:

Push order: `id:1`, `id:2`, `id:3`, `id:4`.
Pop order: `id:1`, `id:4`, `id:3`, `id:2`.

I have made a rough diagram to illustrate the evolution of the heap.

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/722609/125448716-daa9081f-64bf-481f-b858-f12476de2e30.png">

Hope it helps. Let me know if you have further questions about it.

Thanks for your question @ash0080 , as a _heap fan_ I love this kind of conversations.
