### ISSUE TITLE
remove(o) should be O(lgn) but is implemented as O(n)

### ISSUE THREAD

**Issue by ozyman42** [ignlg/heap-js#644]
There should be an internal map from item reference to item's index, remove the item, then heapify.
Current implementation searches through the entire heap array for the element.

**Comment by ignlg** [comment]
I am working on this feature request.

The main issue with your proposal is that it only works if elements are unique or, at least, it needs to be defined what to do when the number of elements that pass the equality check is greater than 1.

My first approach is to add an `indexOf(needle)` method to get the index of the first element of the heap that matches the provided needle. It must go through the heap using the advantages of the heap structure to avoid going through the entire array, which, as you said, is inefficient.
